Contact.create!([
  {first_name: "Hubert", last_name: "McCullough", string: nil, phone_number: "406-940-8677", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Hermina", last_name: "Hudson", string: nil, phone_number: "1-717-511-6844", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Arden", last_name: "Lemke", string: nil, phone_number: "1-468-878-2487", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Gus", last_name: "Moen", string: nil, phone_number: "1-681-688-9750", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Tristan", last_name: "Keebler", string: nil, phone_number: "(911) 632-2749", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Irmgard", last_name: "Toy", string: nil, phone_number: "1-535-338-8595", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Adella", last_name: "Kilback", string: nil, phone_number: "712.750.6512", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Laquanda", last_name: "Bernhard", string: nil, phone_number: "203-796-4500", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Alberto", last_name: "Wuckert", string: nil, phone_number: "(541) 853-6930", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Reta", last_name: "Jacobi", string: nil, phone_number: "1-327-339-4296", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Erlene", last_name: "Bergnaum", string: nil, phone_number: "882.478.5231", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Luigi", last_name: "Fay", string: nil, phone_number: "855.004.5393", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Sharyn", last_name: "Bednar", string: nil, phone_number: "741.638.7454", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Theo", last_name: "Torres", string: nil, phone_number: "234434", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Theo", last_name: "Torres", string: nil, phone_number: "234434", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Theo", last_name: "Torres", string: nil, phone_number: "234434", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Theo", last_name: "Torres", string: nil, phone_number: "234434", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Theo", last_name: "Torres", string: nil, phone_number: "234434", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Theo", last_name: "Torres", string: nil, phone_number: "234434", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "", string: nil, phone_number: "", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: nil, last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Gabriel", last_name: "Torres", string: nil, phone_number: "2343445545", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Elcia", last_name: "Cordeiro", string: nil, phone_number: "9144739680", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Stella", last_name: "Silva", string: nil, phone_number: "2303044050", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Stella", last_name: "Silva", string: nil, phone_number: "2303044050", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: nil, last_name: nil, string: nil, phone_number: nil, middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: nil, last_name: nil, string: nil, phone_number: nil, middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: nil, last_name: nil, string: nil, phone_number: nil, middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: nil, last_name: nil, string: nil, phone_number: nil, middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: nil, last_name: nil, string: nil, phone_number: nil, middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Stella", last_name: "Silva", string: nil, phone_number: "2303044050", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Stella", last_name: "Silva", string: nil, phone_number: "2303044050", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Linwood", last_name: "Torres", string: nil, phone_number: "2343445545", middle_name: "Cordeiro", bio: nil, latitude: nil, longitude: nil},
  {first_name: "Norman", last_name: "Sauer", string: nil, phone_number: "698.925.5726", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Dale", last_name: "Becker", string: nil, phone_number: "1-666-815-2350", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Denver", last_name: "Cormier", string: nil, phone_number: "100.186.3704", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Chris", last_name: "Kautzer", string: nil, phone_number: "1-653-600-9479", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Lance", last_name: "Jacobs", string: nil, phone_number: "723.712.1122", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Kelli", last_name: "Haley", string: nil, phone_number: "972-332-8360", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Keenan", last_name: "Connelly", string: nil, phone_number: "(447) 153-9674", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Lang", last_name: "Weimann", string: nil, phone_number: "(642) 743-6298", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Cristin", last_name: "Rosenbaum", string: nil, phone_number: "330.452.4584", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Cecile", last_name: "Toy", string: nil, phone_number: "336.447.4854", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Burt", last_name: "Funk", string: nil, phone_number: "434.022.8921", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Else", last_name: "Erdman", string: nil, phone_number: "221-488-0337", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Junior", last_name: "Jast", string: nil, phone_number: "694.172.4859", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Kimbery", last_name: "O'Reilly", string: nil, phone_number: "879-063-5135", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Walker", last_name: "Pacocha", string: nil, phone_number: "211.328.9731", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Mariella", last_name: "Yost", string: nil, phone_number: "(733) 232-7690", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Carol", last_name: "Ondricka", string: nil, phone_number: "1-673-122-9475", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Magdalena", last_name: "Gottlieb", string: nil, phone_number: "1-137-064-4394", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Olen", last_name: "Feil", string: nil, phone_number: "1-930-016-8454", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Julius", last_name: "Funk", string: nil, phone_number: "545.913.4811", middle_name: nil, bio: nil, latitude: nil, longitude: nil},
  {first_name: "Vanetta", last_name: "Torres", string: nil, phone_number: "2343445545", middle_name: "Cordeiro", bio: nil, latitude: "40.73105", longitude: "0.0"}
])
